// packages/docs-md/src/lit/components/SectionTitle/SectionTitle.ts
import clsx from "clsx";
import { html } from "lit";
import { customElement, property } from "lit/decorators.js";

import { ExtendedLitElement } from "../util.ts";

@customElement("speakeasy-section-title")
export class SectionTitle extends ExtendedLitElement {
  @property()
  variant = "primary";

  @property()
  override id = "";

  @property()
  override slot = "";

  public override render() {
    super.render();

    return html`<div
      id=${this.id}
      class=${clsx(
        "speakeasy-section-title--title",
        this.variant === "breakout" && "speakeasy-section-title--breakout",
        this.variant === "top-level" && "speakeasy-section-title--topLevel"
      )}
      slot=${this.slot}
    >
      ${this.variant === "breakout"
        ? html`<div class=${clsx("speakeasy-section-title--breakoutLine")} />`
        : ""}
      ${this.children}
    </div>`;
  }
}

// packages/docs-md/src/runtime/components/SectionTitle/SectionTitle.tsx
import clsx from "clsx";
import type { PropsWithChildren } from "react";

import type { SectionVariant } from "../../../renderers/base/base.ts";
import styles from "./styles.module.css";

export type SectionTitleProps = PropsWithChildren<{
  id?: string;
  variant: SectionVariant;
  slot: "title";
}>;

export function SectionTitle({
  children,
  slot,
  variant,
  id,
}: SectionTitleProps) {
  return (
    <div
      id={id}
      className={clsx(
        styles.title,
        variant === "breakout" && styles.breakout,
        variant === "top-level" && styles.topLevel
      )}
      slot={slot}
    >
      {variant === "breakout" && <div className={styles.breakoutLine} />}
      {children}
    </div>
  );
}
