// packages/docs-md/src/lit/components/TabbedSection/TabbedSection.ts
import clsx from "clsx";
import { html, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";

import { InternalError } from "../../../util/internalError.ts";
import { ExtendedLitElement } from "../util.ts";

@customElement("speakeasy-tabbed-section-button")
export class TabButton extends LitElement {
  // Disable lit's default shadow DOM
  override createRenderRoot() {
    return this;
  }

  // Declare reactive properties
  @property()
  isActive = false;

  @property()
  onClick: () => void;

  // Render the UI as a function of component state
  public override render() {
    return html` <button
      onClick=${this.onClick}
      className=${clsx(
        "speakeasy-tabbed-section--button",
        this.isActive
          ? "speakeasy-tabbed-section--buttonActive"
          : "speakeasy-tabbed-section--buttonInactive"
      )}
      style=${{
        fontWeight: this.isActive ? "bold" : "normal",
      }}
    >
      ${this.children}
    </button>`;
  }
}

@customElement("speakeasy-tabbed-section")
export class TabbedSection extends ExtendedLitElement {
  #activeTabId: string | null = null;

  // Render the UI as a function of component state
  public override render() {
    super.render();

    const titleChild = this.getUniqueChild("tab-title");
    const tabChildren = this.getChildren("tab");
    const contentChildren = this.getChildren("tab-content");

    if (!this.#activeTabId) {
      // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
      this.#activeTabId = tabChildren[0]!.attributes.getNamedItem("id")!.value;
    }
    const activeChild = contentChildren.find(
      (child) => child.id === this.#activeTabId
    );
    console.log("activeChild", this.#activeTabId, activeChild);

    const tabChildrenWithButtons = tabChildren.map((tabChild) => {
      const id = tabChild.attributes.getNamedItem("id")?.value;
      if (!id) {
        throw new InternalError("Could not get id from tab");
      }
      return html`<speakeasy-tabbed-section-button
        key=${id}
        isActive=${id === this.#activeTabId}
        @click=${() => this.#setActiveTabId(id)}
      >
        ${tabChild}
      </speakeasy-tabbed-section-button>`;
    });

    return html`<speakeasy-section variant="top-level">
      <speakeasy-section-title slot="title" variant="top-level">
        <div class=${clsx("speakeasy-tabbed-section--titleContainer")}>
          <div>${titleChild}</div>
          <div class=${clsx("speakeasy-tabbed-section--tabs")}>
            ${tabChildrenWithButtons}
          </div>
        </div>
      </speakeasy-section-title>
      <speakeasy-section-content slot="content" variant="top-level">
        ${activeChild}
      </speakeasy-section-content>
    </speakeasy-section>`;
  }

  #setActiveTabId(id: string) {
    console.log("setActiveTabId", id);
    this.#activeTabId = id;
    this.requestUpdate();
  }
}

// packages/docs-md/src/components/TabbedSection/docusaurus/TabbedSection.tsx
import clsx from "clsx";
import { useMemo, useState } from "react";

import { InternalError } from "../../../util/internalError.ts";
import { Card } from "../../primitives/docusaurus/Card.tsx";
import sectionStyles from "../../Section/docusaurus/styles.module.css";
import type { TabbedSectionProps } from "../common/types.ts";
import styles from "./styles.module.css";

function TabButton({
  title,
  tooltip,
  isActive,
  onClick,
}: {
  title: string;
  tooltip?: string;
  isActive: boolean;
  onClick: () => void;
}) {
  return (
    <button
      title={tooltip}
      onClick={onClick}
      className={clsx(
        styles.button,
        isActive ? styles.buttonActive : styles.buttonInactive
      )}
      style={{
        fontWeight: isActive ? "bold" : "normal",
      }}
    >
      {title}
    </button>
  );
}

export function DocusaurusTabbedSection({
  title,
  children,
}: TabbedSectionProps) {
  if (children.length === 0) {
    throw new InternalError("TabbedSection must have at least one child");
  }
  const tabInfo = useMemo(() => {
    return children.map(({ props: { title, tooltip } }) => {
      if (!title) {
        throw new InternalError("TabbedSection child title is missing");
      }
      return { title, tooltip };
    });
  }, [children]);

  // Guaranteed to always have at least one due to the check above
  // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
  const [activeTitle, setActiveTitle] = useState(tabInfo[0]!.title);

  const activeChild = useMemo(() => {
    return children.find((child) => child.props.title === activeTitle);
  }, [children, activeTitle]);

  return (
    <Card>
      <div className={sectionStyles.header}>
        <div className={sectionStyles.title}>{title}</div>
        <div style={{ display: "flex", gap: "0.5rem" }}>
          {tabInfo.map(({ title, tooltip }) => (
            <TabButton
              key={title}
              title={title}
              tooltip={tooltip}
              isActive={title === activeTitle}
              onClick={() => setActiveTitle(title)}
            />
          ))}
        </div>
      </div>
      <div>{activeChild}</div>
    </Card>
  );
}
