// packages/react/src/components/ExpandableCell/ExpandableCell.tsx
"use client";

import clsx from "clsx";

// eslint-disable-next-line fast-import/no-restricted-imports -- Confirmed we're using the component as a default only
import { ExpandableCellIcon as DefaultExpandableCellIcon } from "../ExpandableCellIcon/ExpandableCellIcon.tsx";
import styles from "./styles.module.css";
import type { ExpandableCellProps } from "./types.ts";

/**
 * An Expandable cell is part of a schema row. It is responsible for rendering
 * the expandable button used in the tree-view of the schema. Each row always
 * has either one ExpandableCell or one NonExpandableCell, and are always to the
 * right of the connecting cells.
 *
 * We use an expandable cell any time a breakout/property has children (other
 * breakouts/properties) and/or has front matter (description, examples,
 * default value, etc.)
 *
 * Note: this is a controlled component. The initial open/closed state is set by
 * the compiled MDX code, and its state is managed by
 * src/components/ExpandableSection/components/PrefixCells.tsx
 */
export function ExpandableCell({
  isOpen,
  setIsOpen,
  variant,
  ExpandableCellIcon = DefaultExpandableCellIcon,
  headingId,
}: ExpandableCellProps) {
  return (
    <div className={styles.expandableCellContainer}>
      <div className={styles.expandableButtonContainer}>
        <button
          className={clsx(
            styles.expandableButton,
            variant === "property" && styles.expandableButtonCircle
          )}
          aria-expanded={isOpen}
          type="button"
          data-testid={`expandable-cell-button-${headingId}`}
          onClick={() => setIsOpen(!isOpen)}
        >
          <ExpandableCellIcon
            className={styles.expandableChevron}
            style={{
              transform: isOpen ? "rotate(0deg)" : "rotate(-90deg)",
            }}
          />
        </button>
      </div>
      <div className={styles.expandableConnectionContainer}>
        <div className={styles.expandableConnection}></div>
      </div>
    </div>
  );
}

// packages/web-components/src/components/expandable/expandableCell/expandableCell.ts
"use client";

import clsx from "clsx";
import { html, LitElement } from "lit";
import { customElement, property } from "lit/decorators.js";

import type { LitProps } from "../../../types/components.ts";
import { styles as litStyles } from "./styles.ts";

export type ExpandableCellProps = LitProps<ExpandableCell>;

/**
 * An Expandable cell is part of a schema row. It is responsible for rendering
 * the expandable button used in the tree-view of the schema. Each row always
 * has either one ExpandableCell or one NonExpandableCell, and are always to the
 * right of the connecting cells.
 *
 * We use an expandable cell any time a breakout/property has children (other
 * breakouts/properties) and/or has front matter (description, examples,
 * default value, etc.)
 *
 * Note: this is a controlled component. The initial open/closed state is set by
 * the compiled MDX code, and its state is managed by
 * src/components/ExpandableSection/components/PrefixCells.tsx
 */
@customElement("spk-expandable-cell")
export class ExpandableCell extends LitElement {
  static override styles = litStyles;

  /**
   * Whether the cell is currently open or not.
   */
  @property({ type: Boolean })
  public isOpen = false;

  /**
   * The variant of the cell
   */
  @property({ type: String })
  public variant: "breakout" | "property" = "property";

  /**
   * A callback to set the open state of the cell
   */
  @property({ type: Function })
  public setIsOpen?: (isOpen: boolean) => void;

  public override render() {
    return html`<div class="expandableCellContainer">
      <div class="expandableButtonContainer">
        <button
          class=${clsx(
            "expandableButton",
            this.variant === "property" && "expandableButtonCircle"
          )}
          aria-expanded=${this.isOpen}
          type="button"
          @click="${() => this.setIsOpen?.(!this.isOpen)}"
        >
          <spk-expandable-cell-icon
            class="expandableChevron"
            style="transform: ${this.isOpen
              ? "rotate(0deg)"
              : "rotate(-90deg)"};"
          ></spk-expandable-cell-icon>
        </button>
      </div>
      <div class="expandableConnectionContainer">
        <div class="expandableConnection"></div>
      </div>
    </div>`;
  }
}
