// packages/docs-md/src/lit/components/Section/Section.ts
import clsx from "clsx";
import { html } from "lit";
import { customElement, property } from "lit/decorators.js";

import { ExtendedLitElement } from "../util.ts";

@customElement("speakeasy-section")
export class Section extends ExtendedLitElement {
  @property()
  variant = "primary";

  public override render() {
    super.render();

    const titleChild = this.getUniqueChild("title");
    const contentChildren = this.getChildren("content");

    return html`<div
      class=${clsx(this.variant !== "breakout" && "speakeasy-section--section")}
    >
      <div>${titleChild}</div>
      <div
        class=${clsx(
          this.variant === "breakout" && "speakeasy-section--breakout",
          this.variant === "top-level" && "speakeasy-section--topLevel"
        )}
      >
        ${contentChildren}
      </div>
    </div>`;
  }
}

// packages/docs-md/src/components/Section/Section.tsx
import clsx from "clsx";
import type { PropsWithChildren } from "react";

import type { SectionVariant } from "../../renderers/base/base.ts";
import { useChildren, useUniqueChild } from "./hooks.ts";
import styles from "./styles.module.css";

export type SectionProps = PropsWithChildren<{
  variant: SectionVariant;
}>;

export function Section({ children, variant }: SectionProps) {
  const titleChild = useUniqueChild(children, "title");
  const contentChildren = useChildren(children, "content");
  return (
    <div className={styles.section}>
      <div>{titleChild}</div>
      <div
        className={clsx(
          variant === "breakout" && styles.breakout,
          variant === "top-level" && styles.topLevel
        )}
      >
        {contentChildren}
      </div>
    </div>
  );
}
