// packages/react/src/components/NonExpandableCell.tsx
"use client";

import "@speakeasy-api/docs-md-components";

import type { NonExpandableCellProps as NonExpandableCellElementProps } from "@speakeasy-api/docs-md-components";
import type { PropsWithChildren } from "react";

export type NonExpandableCellProps =
  PropsWithChildren<NonExpandableCellElementProps>;

/**
 * A non expandable cell is part of a schema row. It is responsible for
 * rendering the non-expandable button used in the tree-view of the schema. A
 * row is considered non-expandable if it a) has no child breakouts or
 * properties _and_ b) has no front matter. NonExpandableCell takes no props.
 *
 * Each row always has either one ExpandableCell or one NonExpandableCell, and
 * are always to the right of the connecting cells.
 */
export function NonExpandableCell(_: NonExpandableCellProps) {
  return <spk-non-expandable-cell />;
}

// packages/web-components/src/components/expandable/nonExpandableCell/nonExpandableCell.ts
"use client";

import { html, LitElement } from "lit";
import { customElement } from "lit/decorators.js";

import type { LitProps } from "../../../types/components.ts";
import { styles as litStyles } from "./styles.ts";

export type NonExpandableCellProps = LitProps<NonExpandableCell>;

/**
 * A non expandable cell is part of a schema row. It is responsible for
 * rendering the non-expandable button used in the tree-view of the schema. A
 * row is considered non-expandable if it a) has no child breakouts or
 * properties _and_ b) has no front matter. NonExpandableCell takes no props.
 *
 * Each row always has either one ExpandableCell or one NonExpandableCell, and
 * are always to the right of the connecting cells.
 */
@customElement("spk-non-expandable-cell")
export class NonExpandableCell extends LitElement {
  static override styles = litStyles;

  public override render() {
    return html`<span class="nonExpandableCell"></span>`;
  }
}
