// packages/docs-md/src/lit/components/SectionContent/SectionContent.ts
import clsx from "clsx";
import { html } from "lit";
import { customElement, property } from "lit/decorators.js";

import { ExtendedLitElement } from "../util.ts";

@customElement("speakeasy-section-content")
export class SectionContent extends ExtendedLitElement {
  @property()
  variant = "primary";

  @property()
  override id = "";

  @property()
  override slot = "";

  public override render() {
    super.render();

    return html`<div
      class=${clsx(
        "speakeasy-section-content--content",
        this.variant === "breakout" && "speakeasy-section-content--breakout",
        this.variant === "top-level" && "speakeasy-section-content--topLevel"
      )}
      id="${this.id}"
      slot="${this.slot}"
    >
      ${this.children}
    </div>`;
  }
}

// packages/docs-md/src/runtime/components/SectionContent/SectionContent.tsx
import clsx from "clsx";
import type { PropsWithChildren } from "react";

import type { SectionVariant } from "../../../renderers/base/base.ts";
import styles from "./styles.module.css";

export type SectionContentProps = PropsWithChildren<{
  id?: string;
  slot: "content";
  variant: SectionVariant;
}>;

export function SectionContent({
  slot,
  variant,
  children,
  id,
}: SectionContentProps) {
  return (
    <div
      className={clsx(
        styles.content,
        variant === "breakout" && styles.breakout,
        variant === "top-level" && styles.topLevel
      )}
      id={id}
      slot={slot}
    >
      {children}
    </div>
  );
}
